Repository kmaooad/capstone23, pull requests merged in 2023-10, with the labels that each got.

#159 [Chats]: Setup creation flow with test coverage
  app/src/main/java/edu/kmaooad/capstone23/common/Event.java
  app/src/main/java/edu/kmaooad/capstone23/communication/commands/CreateChat.java
  app/src/main/java/edu/kmaooad/capstone23/communication/controllers/CreateChatController.java
  app/src/main/java/edu/kmaooad/capstone23/communication/dal/entities/Chat.java
  app/src/main/java/edu/kmaooad/capstone23/communication/dal/entities/Participant.java
  app/src/main/java/edu/kmaooad/capstone23/communication/dal/repositories/ChatRepository.java
  app/src/main/java/edu/kmaooad/capstone23/communication/dal/repositories/ParticipantRepository.java
  app/src/main/java/edu/kmaooad/capstone23/communication/events/ChatCreated.java
  app/src/main/java/edu/kmaooad/capstone23/communication/handlers/CreateChatHandler.java
  app/src/main/java/edu/kmaooad/capstone23/users/dal/entities/User.java
  app/src/main/java/edu/kmaooad/capstone23/users/dal/repositories/UserRepository.java
  app/src/test/java/edu/kmaooad/capstone23/access_rules/handlers/CreateAccessRuleHandlerTests.java
  app/src/test/java/edu/kmaooad/capstone23/common/ControllerTest.java
  app/src/test/java/edu/kmaooad/capstone23/common/HandlerTest.java
  app/src/test/java/edu/kmaooad/capstone23/communication/controllers/CreateChatControllerTest.java
  app/src/test/java/edu/kmaooad/capstone23/communication/handlers/CreateChatHandlerTest.java
  app/src/test/java/edu/kmaooad/capstone23/communication/mocks/ChatMocks.java
  app/src/test/java/edu/kmaooad/capstone23/orgs/members/handlers/CreateMemberHandlerTest.java
  app/src/test/java/edu/kmaooad/capstone23/orgs/members/handlers/GetAllMembersHandlerTest.java
Labels: Chats

#161 [Participants]: Setup creation flow with test coverage
  app/src/main/java/edu/kmaooad/capstone23/common/ObjectMapperSerializingToHexObjectId.java
  app/src/main/java/edu/kmaooad/capstone23/communication/commands/CreateParticipant.java
  app/src/main/java/edu/kmaooad/capstone23/communication/controllers/CreateParticipantController.java
  app/src/main/java/edu/kmaooad/capstone23/communication/events/ParticipantCreated.java
  app/src/main/java/edu/kmaooad/capstone23/communication/handlers/CreateChatHandler.java
  app/src/main/java/edu/kmaooad/capstone23/communication/handlers/CreateParticipantHandler.java
  app/src/main/java/edu/kmaooad/capstone23/communication/services/ChatService.java
  app/src/main/java/edu/kmaooad/capstone23/communication/services/ParticipantService.java
  app/src/main/java/edu/kmaooad/capstone23/users/services/UserService.java
  app/src/test/java/edu/kmaooad/capstone23/access_rules/handlers/CreateAccessRuleHandlerTests.java
  app/src/test/java/edu/kmaooad/capstone23/common/ControllerTest.java
  app/src/test/java/edu/kmaooad/capstone23/common/Mocks.java
  app/src/test/java/edu/kmaooad/capstone23/communication/controllers/CreateParticipantControllerTest.java
  app/src/test/java/edu/kmaooad/capstone23/communication/handlers/CreateParticipantHandlerTest.java
  app/src/test/java/edu/kmaooad/capstone23/communication/mocks/ParticipantMocks.java
  app/src/test/java/edu/kmaooad/capstone23/orgs/members/handlers/CreateMemberHandlerTest.java
  app/src/test/java/edu/kmaooad/capstone23/orgs/members/handlers/GetAllMembersHandlerTest.java
  app/src/test/java/edu/kmaooad/capstone23/users/mocks/UserMocks.java
Labels: Chats, Participants

#162 [Users]: Setup creation flow with test coverage
  app/src/main/java/edu/kmaooad/capstone23/users/commands/CreateUser.java
  app/src/main/java/edu/kmaooad/capstone23/users/controllers/CreateUserController.java
  app/src/main/java/edu/kmaooad/capstone23/users/events/UserCreated.java
  app/src/main/java/edu/kmaooad/capstone23/users/handlers/CreateUserHandler.java
  app/src/test/java/edu/kmaooad/capstone23/common/HandlerTest.java
  app/src/test/java/edu/kmaooad/capstone23/common/Mocks.java
  app/src/test/java/edu/kmaooad/capstone23/communication/handlers/CreateChatHandlerTest.java
  app/src/test/java/edu/kmaooad/capstone23/communication/handlers/CreateParticipantHandlerTest.java
  app/src/test/java/edu/kmaooad/capstone23/communication/mocks/ChatMocks.java
  app/src/test/java/edu/kmaooad/capstone23/users/controllers/CreateUserControllerTest.java
  app/src/test/java/edu/kmaooad/capstone23/users/handlers/CreateUserHandlerTest.java
  app/src/test/java/edu/kmaooad/capstone23/users/mocks/UserMocks.java
Labels: Chats, Participants, Users

#206 [Chats]: Setup bulk-creation flow with test coverage
  app/src/main/java/edu/kmaooad/capstone23/communication/commands/BulkCreateChats.java
  app/src/main/java/edu/kmaooad/capstone23/communication/controllers/BulkCreateChatsController.java
  app/src/main/java/edu/kmaooad/capstone23/communication/dal/repositories/ChatRepository.java
  app/src/main/java/edu/kmaooad/capstone23/communication/events/ChatsBulkCreated.java
  app/src/main/java/edu/kmaooad/capstone23/communication/handlers/BulkCreateChatsHandler.java
  app/src/test/java/edu/kmaooad/capstone23/common/HandlerTest.java
  app/src/test/java/edu/kmaooad/capstone23/communication/controllers/BulkCreateChatsControllerTest.java
  app/src/test/java/edu/kmaooad/capstone23/communication/handlers/BulkCreateChatsHandlerTest.java
  app/src/test/java/edu/kmaooad/capstone23/communication/mocks/ChatMocks.java
  app/src/test/java/edu/kmaooad/capstone23/communication/utils/ChatsListWrapper.java
Labels: Chats

#158 Feature/find activities by skill controller
  app/src/main/java/edu/kmaooad/capstone23/search/courses/by/skill/controllers/QueryCourseBySkillController.java
  app/src/main/java/edu/kmaooad/capstone23/search/courses/by/skill/events/CourseQueriedBySkill.java
  app/src/main/java/edu/kmaooad/capstone23/search/courses/by/skill/handlers/QueryCourseBySkillHandler.java
  app/src/test/java/edu/kmaooad/capstone23/search/courses/by/skill/controllers/QueryCourseBySkillControllerTests.java
  app/src/test/java/edu/kmaooad/capstone23/search/courses/by/skill/handlers/QueryCourseBySkillHandlerTests.java
Labels: enhancement

#216 Feature/find courses by skillset handler
  app/src/main/java/edu/kmaooad/capstone23/search/courses/by/skillset/events/CourseQueriedBySkillSet.java
  app/src/main/java/edu/kmaooad/capstone23/search/courses/by/skillset/handlers/QueryCourseBySkillSetHandler.java
  app/src/test/java/edu/kmaooad/capstone23/search/courses/by/skillset/handlers/QueryCourseBySkillSetHandlerTest.java
Labels: enhancement

#156 Feature/find courses by dept controller
  app/src/main/java/edu/kmaooad/capstone23/search/courses/by/department/controllers/QueryCourseByDepartmentController.java
  app/src/test/java/edu/kmaooad/capstone23/search/courses/by/department/controllers/QueryCourseByDepartmentControllerTest.java
Labels: enhancement

#289 Feature/find extracurricular activities by group
  app/src/main/java/edu/kmaooad/capstone23/search/extracurricularActivities/by/group/events/ExtracurricularActivityQueriedByGroup.java
  app/src/main/java/edu/kmaooad/capstone23/search/extracurricularActivities/by/group/handlers/QueryExtracurricularActivitiesByGroupHandler.java
  app/src/test/java/edu/kmaooad/capstone23/search/extracurricularActivities/by/group/handlers/QueryExtracurricularActivitiesByGroupHandlerTest.java
Labels: enhancement

#287 Feature/find courses by topic handler
  app/src/main/java/edu/kmaooad/capstone23/search/courses/by/topic/events/CourseQueriedByTopic.java
  app/src/main/java/edu/kmaooad/capstone23/search/courses/by/topic/handlers/QueryCourseByTopicHandler.java
  app/src/test/java/edu/kmaooad/capstone23/search/courses/by/topic/handlers/QueryCourseByTopicHandlerTest.java
Labels: enhancement

#237 Feature/find courses by project handler
  app/src/main/java/edu/kmaooad/capstone23/search/courses/by/project/events/CourseQueriedByProject.java
  app/src/main/java/edu/kmaooad/capstone23/search/courses/by/project/handlers/QueryCourseByProjectHandler.java
  app/src/test/java/edu/kmaooad/capstone23/search/courses/by/project/handlers/QueryCourseByProjectHandlerTest.java
Labels: enhancement

#238 Feature/find courses by project controller
  app/src/main/java/edu/kmaooad/capstone23/search/courses/by/project/controllers/QueryCourseByProjectController.java
  app/src/test/java/edu/kmaooad/capstone23/search/courses/by/project/controllers/QueryCourseByProjectControllerTests.java
Labels: enhancement

#288 Feature/find courses by topic controller
  app/src/main/java/edu/kmaooad/capstone23/search/courses/by/topic/controllers/QueryCourseByTopicController.java
  app/src/test/java/edu/kmaooad/capstone23/search/courses/by/topic/controllers/QueryCourseByTopicControllerTest.java
Labels: enhancement
